apiVersion: v1
kind: Service
metadata:
  name: ksqldb-headless
  namespace: proc-layer
spec:
  clusterIP: None
  selector:
    app: ksqldb-server

  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088