apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: $DEPLOYMENT
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: $DEPLOYMENT-neo4j-core-$IDX
  name: $DEPLOYMENT-neo4j-external-$IDX
spec:
  loadBalancerIP: $IP
  externalTrafficPolicy: Local
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: https
    port: 7473
    protocol: TCP
    targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: $DEPLOYMENT-neo4j-core-$IDX
  sessionAffinity: None
  type: LoadBalancer
