apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bot-flights
spec:
  schedule: "47 19 * * *"
  jobTemplate:
    spec:
      parallelism: 3
      completions: 1
      template:
        spec:
          containers:
          - name: bot-flights
            image: lferreira1337/automation-projects:botflights-1.0.7
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
  concurrencyPolicy: Allow        
       
