apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bot-flights
spec:
  schedule: "0 0-23/2 * * *"
  jobTemplate:
    spec:
      parallelism: 8
      completions: 1
      template:
        spec:
          containers:
          - name: bot-flights
            image: lferreira1337/automation-projects:botflights-1.0.5
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
       
