apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bot-flights
spec:
  schedule: "25 02 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bot-flights
            image: lferreira1337/automation-projects:botflights-1.0.3
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
       
