apiVersion: v1
description: Multi-Cloud Object Storage
name: minio
version: 3.4.3
appVersion: RELEASE.2021-12-20T22-07-16Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
