apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: minio
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/magal1337/k8s-projects.git'
    path: k8s-arch/minio-official-arch/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: storage-layer
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
