apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    app: airflow-logs
spec:
  storageClassName: do-block-storage

  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflow-logs
    namespace: orch-layer
  hostPath:
    path:  ./data
  #ContainerPath:
    #path: /opt/airflow/data