apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: orch-layer
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.2.0
    component: logs-pvc
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-logs
  namespace: orch-layer
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem
